/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class AddResults extends javax.swing.JPanel {

    private Main main;

    /**
     * Creates new form AddResults
     */
    public AddResults() {
        initComponents();
    }

    AddResults(Main main) {
        initComponents();
        this.main=main;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        j = new javax.swing.JTextField();
        k = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        addresults = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD RESULTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel5.setText("NIC NUMBER :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, 50));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setText("YEAR :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 270, 50));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setText("SEMESTER :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 270, 50));

        semester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, 40));

        nic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 280, 40));

        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, 40));

        i.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 60, 30));

        b.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 160, 30));

        d.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 160, 30));

        e.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 160, 30));

        g.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 160, 30));

        c.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 160, 30));

        f.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 160, 30));

        a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 160, 30));

        j.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });
        add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 60, 30));

        k.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });
        add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 60, 30));

        l.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });
        add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 60, 30));

        m.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 60, 30));

        n.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 60, 30));

        h.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 60, 30));

        addresults.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addresults.setText("ADD RESULTS");
        add(addresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 180, 40));

        cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JButton addresults;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextField h;
    private javax.swing.JTextField i;
    private javax.swing.JTextField j;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField k;
    private javax.swing.JTextField l;
    private javax.swing.JTextField m;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField semester;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
