/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import static nsbm.Main.load;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class BComputing extends javax.swing.JPanel {

    private Main main;
    private UStudent u;
    /**
     * Creates new form BComputing
     */
    public BComputing(UStudent u) {
        this.u = u;
        initComponents();
    }

    BComputing(Main main) {
        initComponents();
        this.main=main;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fsub2 = new javax.swing.JComboBox<>();
        fsub3 = new javax.swing.JComboBox<>();
        fsub1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ssub2 = new javax.swing.JComboBox<>();
        ssub3 = new javax.swing.JComboBox<>();
        ssub1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT INFORMATION SHEET 03", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("09) SELECT SUBJECTS :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 360, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("* THE SUBJECT CARRIES 2(FOR OPTIONAL) OR 3 CREDITS. ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 550, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("* YOU SHOULD COMPLETE 30 CREDITS IN EACH ACADEMIC YEAR.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 550, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 20, 440));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("FOR SECOND SEMESTER");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, 230, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FOR FIRST SEMESTER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 230, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("BC 1203");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 410, 200, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("BC 1201");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 330, 200, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("BC 1202");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 370, 200, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("BC 1103");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 200, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("BC 1101");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 200, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("BC 1102");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 200, 40));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 680, 230, 60));

        submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 680, 230, 60));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("SUBJECT 02 :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 200, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("SUBJECT 03 :");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 200, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("SUBJECT 04 :");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 200, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("SUBJECT 05 :");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 200, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("SUBJECT 06 :");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 200, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("SUBJECT 01 :");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, 40));

        fsub2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fsub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC 1107", "BC 1108", "BC 1109" }));
        add(fsub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 150, 30));

        fsub3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fsub3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC 1110", "BC 1111", "BC 1112" }));
        add(fsub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 150, 30));

        fsub1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fsub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC 1104", "BC 1105", "BC 1106" }));
        add(fsub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 150, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("SUBJECT 02 :");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 200, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("SUBJECT 03 :");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 200, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("SUBJECT 04 :");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 200, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("SUBJECT 05 :");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 200, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("SUBJECT 06 :");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 530, 200, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("SUBJECT 01 :");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, 200, 40));

        ssub2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ssub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC 1207", "BC 1208", "BC 1209" }));
        add(ssub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 500, 150, 30));

        ssub3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ssub3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC 1210", "BC 1211", "BC 1212" }));
        add(ssub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 540, 150, 30));

        ssub1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ssub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC 1204", "BC 1205", "BC 1206" }));
        add(ssub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 460, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void fillUStudent() {
        u.setFSubject1((String)fsub1.getSelectedItem());
        u.setFSubject2((String)fsub2.getSelectedItem());
        u.setFSubject3((String)fsub3.getSelectedItem());
        u.setSSubject1((String)ssub1.getSelectedItem());
        u.setSSubject2((String)ssub2.getSelectedItem());
        u.setSSubject3((String)ssub3.getSelectedItem());
    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        StudentForm2 object = new StudentForm2(u);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
        fillUStudent();
        DBconnection.addUStudent(u);
        JOptionPane.showMessageDialog(null, "SUCCESSFULL!!!");
        Home object = new Home();   
        load.removeAll();
        load.add(object);
        load.repaint();
        load.revalidate();
        object.setVisible(true);
        }
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> fsub1;
    private javax.swing.JComboBox<String> fsub2;
    private javax.swing.JComboBox<String> fsub3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> ssub1;
    private javax.swing.JComboBox<String> ssub2;
    private javax.swing.JComboBox<String> ssub3;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
