package nsbm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pramuditha Kaushalya
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        super("NSBM Enroll Management");
        initComponents();
        homeBtn.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        load = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subject = new javax.swing.JButton();
        instructor = new javax.swing.JButton();
        lecturer = new javax.swing.JButton();
        student = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        viewresults = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addresults = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        load.setLayout(new java.awt.BorderLayout());
        load.add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        jPanel1.add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 1580, 770));

        subject.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        subject.setText("SUBJECT");
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 250, 50));

        instructor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        instructor.setText("INSTRUCTOR");
        instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorActionPerformed(evt);
            }
        });
        jPanel1.add(instructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 250, 50));

        lecturer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lecturer.setText("LECTURER");
        lecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerActionPerformed(evt);
            }
        });
        jPanel1.add(lecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 250, 50));

        student.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        student.setText("STUDENT");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        jPanel1.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NATIONAL SCHOOL OF BUSINESS MANAGEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 1200, 150));

        logout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 900, 250, 50));

        homeBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, 50));

        viewresults.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewresults.setText("VIEW RESULTS");
        viewresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewresultsActionPerformed(evt);
            }
        });
        jPanel1.add(viewresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 250, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramuditha Kaushalya\\Pictures\\NSBM1.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 140));

        addresults.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addresults.setText("ADD RESULTS");
        addresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresultsActionPerformed(evt);
            }
        });
        jPanel1.add(addresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        Subject object = new Subject();   
        load.removeAll();
        load.add(object);
        load.repaint();
        load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_subjectActionPerformed

    private void instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorActionPerformed
        Instructor instructorForm = new Instructor(this);
        load.removeAll();
        load.add(instructorForm);
        load.repaint();
        load.revalidate();
        instructor.setVisible(true);
    }//GEN-LAST:event_instructorActionPerformed

    private void lecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerActionPerformed
        LecturerForm lecturerForm = new LecturerForm();
        load.removeAll();
        load.add(lecturerForm);
        load.repaint();
        load.revalidate();
        lecturerForm.setVisible(true);
    }//GEN-LAST:event_lecturerActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        Student studentForm = new Student(this);
        load.removeAll();
        load.add(studentForm);
        load.repaint();
        load.revalidate();
        studentForm.setVisible(true);
    }//GEN-LAST:event_studentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login object = new Login();
        object.setVisible(true);
        
      
    }//GEN-LAST:event_logoutActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Home object = new Home();   
        load.removeAll();
        load.add(object);
        load.repaint();
        load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void viewresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewresultsActionPerformed
        // TODO add your handling code here:
        Results object = new Results(this);
        load.removeAll();
        load.add(object);
        load.repaint();
        load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_viewresultsActionPerformed

    private void addresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresultsActionPerformed
        // TODO add your handling code here:
        AddResults object = new AddResults(this);
        load.removeAll();
        load.add(object);
        load.repaint();
        load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_addresultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addresults;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton instructor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lecturer;
    public static javax.swing.JPanel load;
    private javax.swing.JButton logout;
    private javax.swing.JButton student;
    private javax.swing.JButton subject;
    private javax.swing.JButton viewresults;
    // End of variables declaration//GEN-END:variables
}
