/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import static nsbm.Main.load;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class MComputing extends javax.swing.JPanel {

    private Main main;
    private PStudent p;
    
    /**
     * Creates new form MComputing
     */
    public MComputing(PStudent p) {
        this.p = p;
        initComponents();
    }

    MComputing(Main main) {
        initComponents();
        this.main=main;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sub2 = new javax.swing.JComboBox<>();
        sub3 = new javax.swing.JComboBox<>();
        sub1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sub5 = new javax.swing.JComboBox<>();
        sub6 = new javax.swing.JComboBox<>();
        sub4 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT INFORMAION SHEET 03", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("09) SELECT SUBJECTS :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 360, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("* THE SUBJECT CARRIES 2(FOR OPTIONAL) OR 3 CREDITS. ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 550, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("* YOU SHOULD COMPLETE 24 CREDITS IN EACH ACADEMIC YEAR.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 550, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 20, 440));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("FOR SECOND SEMESTER");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, 230, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FOR FIRST SEMESTER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 230, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("MC 1201");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 330, 200, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("MC 1202");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 370, 200, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("MC 1101");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 200, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("MC 1102");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 200, 40));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 680, 230, 60));

        submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 680, 230, 60));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("SUBJECT 02 :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 200, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("SUBJECT 03 :");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 200, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("SUBJECT 04 :");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 200, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("SUBJECT 05 :");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 200, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("SUBJECT 01 :");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, 40));

        sub2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MC 1106", "MC 1107", "MC 1108" }));
        add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 150, 30));

        sub3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MC 1109", "MC 1110", "MC 1111" }));
        add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 150, 30));

        sub1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MC 1103", "MC 1104", "MC 1105" }));
        add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 150, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("SUBJECT 02 :");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 200, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("SUBJECT 03 :");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 200, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("SUBJECT 04 :");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 200, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("SUBJECT 05 :");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 200, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("SUBJECT 01 :");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, 200, 40));

        sub5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MC 1106", "MC 1107", "MC 1108" }));
        add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 460, 150, 30));

        sub6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MC 1109", "MC 1110", "MC 1111" }));
        add(sub6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 500, 150, 30));

        sub4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sub4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MC 1203", "MC 1204", "MC 1205" }));
        add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 420, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void fillUStudent() {
        p.setSubject1((String)sub1.getSelectedItem());
        p.setSubject2((String)sub2.getSelectedItem());
        p.setSubject3((String)sub3.getSelectedItem());
        p.setSubject4((String)sub4.getSelectedItem());
        p.setSubject5((String)sub5.getSelectedItem());
        p.setSubject6((String)sub6.getSelectedItem());
    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        PStudentForm2 object = new PStudentForm2();
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         try{
        fillUStudent();
        DBconnection.addPStudent(p); 
        JOptionPane.showMessageDialog(null, "SUCCESSFULL!!!");
        Home object = new Home();   
        load.removeAll();
        load.add(object);
        load.repaint();
        load.revalidate();
        object.setVisible(true);
        }
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> sub1;
    private javax.swing.JComboBox<String> sub2;
    private javax.swing.JComboBox<String> sub3;
    private javax.swing.JComboBox<String> sub4;
    private javax.swing.JComboBox<String> sub5;
    private javax.swing.JComboBox<String> sub6;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
