/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Pramuditha Kaushalya
 */
public class PStudentForm2 extends javax.swing.JPanel {

    private Main main;
    private PStudent p;
    
    /**
     * Creates new form PStudentForm2
     */
    public PStudentForm2(PStudent p) {
        this.p=p;
        initComponents();
    }

    PStudentForm2(Main main) {
        initComponents();
        this.main=main;
    }

    PStudentForm2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        institute = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        digdip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MCom = new javax.swing.JButton();
        MBus = new javax.swing.JButton();
        MEng = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "POSTGRADUATE STUDENT FORM 02", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel8.setText("07) PREVIOUS EDUCATION RECORDS :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 470, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("INSTITUTE :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 170, 30));

        institute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(institute, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 410, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("YEAR OF COMPLETION :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 230, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("DEGREE/DIP :");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 170, 30));

        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 130, 30));

        digdip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(digdip, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 410, 30));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setText("08) SELECT COURSE :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 360, 40));

        MCom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MCom.setText("Msc. in COMPUTING");
        MCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MComActionPerformed(evt);
            }
        });
        add(MCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 310, 50));

        MBus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MBus.setText("Msc. in BUSINESS");
        MBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBusActionPerformed(evt);
            }
        });
        add(MBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 310, 50));

        MEng.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MEng.setText("Msc. in ENGINEERING");
        MEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEngActionPerformed(evt);
            }
        });
        add(MEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 310, 50));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 650, 230, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 20, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void fillPStudent(){
        p.setDigDip(digdip.getText());
        p.setInstitute(institute.getText());
        p.setYear(Integer.parseInt(year.getText()));
    }
    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void MComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MComActionPerformed
        // TODO add your handling code here:
        fillPStudent();
        MComputing object = new MComputing(p);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_MComActionPerformed

    private void MBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBusActionPerformed
        // TODO add your handling code here:
        fillPStudent();
        MBusiness object = new MBusiness(p);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_MBusActionPerformed

    private void MEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEngActionPerformed
        // TODO add your handling code here:
        fillPStudent();
        MEngineering object = new MEngineering(p);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_MEngActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        PStudentForm object = new PStudentForm();
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MBus;
    private javax.swing.JButton MCom;
    private javax.swing.JButton MEng;
    private javax.swing.JButton back;
    private javax.swing.JTextField digdip;
    private javax.swing.JTextField institute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
