/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static nsbm.Main.load;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class PStudentForm extends javax.swing.JPanel {

    private Main main;
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    /**
     * Creates new form PStudentForm
     */
    public PStudentForm() {
        initComponents();
        conn = DBconnection.connection();
    }

    PStudentForm(Main main) {
        initComponents();
        this.main=main;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        home = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        intake = new javax.swing.JComboBox<>();
        next = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "POSTGRADUATE STUDENT FORM 01", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setText("01) NAME IN FULL :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 270, 50));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel3.setText("02) NIC NUMBER :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 270, 50));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setText("03) ADDRESS :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 270, 50));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel5.setText("04) CONTACT :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 270, 50));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setText("06) INTAKE :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 270, 50));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 980, 50));

        nic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 300, 50));

        mobile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 310, 50));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 690, 50));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 690, 140));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setText("MOBILE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 440, 140, 30));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setText("HOME");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 140, 30));

        home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 310, 50));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel12.setText("05)  EMAIL :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 270, 50));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 680, 230, 60));

        intake.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEBRUARY", "JULY" }));
        intake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeActionPerformed(evt);
            }
        });
        add(intake, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 310, 50));

        next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 680, 230, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        clearText();
        Student studentForm = new Student();
        load.removeAll();
        load.add(studentForm);
        load.repaint();
        load.revalidate();
        studentForm.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        PStudent p = new PStudent();
        p.setName(name.getText());
        p.setNic((String)nic.getText());
        p.setAddress(address.getText());
        p.setHome(Integer.parseInt(home.getText()));
        p.setMobile(Integer.parseInt(mobile.getText()));
        p.setEmail(email.getText());
        p.setIntake((String)intake.getSelectedItem());
        PStudentForm2 object = new PStudentForm2(p);     
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
        
    }//GEN-LAST:event_nextActionPerformed

    private void intakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intakeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JButton back;
    private javax.swing.JTextField email;
    private javax.swing.JTextField home;
    private javax.swing.JComboBox<String> intake;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JButton next;
    private javax.swing.JTextField nic;
    // End of variables declaration//GEN-END:variables

private void clearText(){
        name.setText("");
        nic.setText("");
        address.setText("");
        home.setText("");
        mobile.setText("");
        email.setText("");
    }
}
