/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import static nsbm.Main.load;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class StudentForm2 extends javax.swing.JPanel {

    private Main main;
    private UStudent u;
    /**
     * Creates new form StudentForm2
     */
    public StudentForm2(UStudent u) {
        this.u = u;
        initComponents();
    }
    
    StudentForm2(Main main) {
        initComponents();
        this.main=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        index = new javax.swing.JTextField();
        zcore = new javax.swing.JTextField();
        irank = new javax.swing.JTextField();
        drank = new javax.swing.JTextField();
        ALyear = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stream = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bcom = new javax.swing.JButton();
        bbusi = new javax.swing.JButton();
        beng = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UNDERGRADUATE STUDENT FORM 02", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 20, 430));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel8.setText("07) PREVIOUS EDUCATION RECORDS :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 470, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("STREAM :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Z-CORE :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("I RANK :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("INDEX NUMBER :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("A/L YEAR :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 170, 30));

        index.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(index, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 190, 30));

        zcore.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(zcore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 190, 30));

        irank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(irank, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 190, 30));

        drank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(drank, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 190, 30));

        ALyear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ALyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALyearActionPerformed(evt);
            }
        });
        add(ALyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 190, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("D RANK :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 170, 30));

        stream.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stream.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATHS", "BIO", "COMMERCE", "ARTS", "TECHNOLOGY", "OTHER" }));
        stream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streamActionPerformed(evt);
            }
        });
        add(stream, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 190, 30));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 650, 230, 60));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("08) SELECT COURSE :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 360, 40));

        bcom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bcom.setText("Bsc. in COMPUTING");
        bcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcomActionPerformed(evt);
            }
        });
        add(bcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 310, 50));

        bbusi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bbusi.setText("Bsc. in BUSINESS");
        bbusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbusiActionPerformed(evt);
            }
        });
        add(bbusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 310, 50));

        beng.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        beng.setText("Bsc. in ENGINEERING");
        beng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bengActionPerformed(evt);
            }
        });
        add(beng, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 310, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void fillUStudent() {
        u.setALyear(Integer.parseInt(ALyear.getText()));
        u.setIndexNum(Integer.parseInt(index.getText()));
        u.setZcore(Double.parseDouble(zcore.getText()));
        u.setIRank(Integer.parseInt(irank.getText()));
        u.setDrank(Integer.parseInt(drank.getText()));
        u.setStream(stream.getSelectedItem().toString());
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        StudentForm studentForm = new StudentForm();
        main.load.removeAll();
        main.load.add(studentForm);
        main.load.repaint();
        main.load.revalidate();
        studentForm.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void bcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcomActionPerformed
        // TODO add your handling code here:
        fillUStudent();
        BComputing object = new BComputing(u);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_bcomActionPerformed

    private void bbusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbusiActionPerformed
        // TODO add your handling code here:
        fillUStudent();
        BBusiness object = new BBusiness(u);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_bbusiActionPerformed

    private void bengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bengActionPerformed
        // TODO add your handling code here:
        fillUStudent();
        BEngineering object = new BEngineering(u);
        main.load.removeAll();
        main.load.add(object);
        main.load.repaint();
        main.load.revalidate();
        object.setVisible(true);
    }//GEN-LAST:event_bengActionPerformed

    private void ALyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALyearActionPerformed

    private void streamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALyear;
    private javax.swing.JButton back;
    private javax.swing.JButton bbusi;
    private javax.swing.JButton bcom;
    private javax.swing.JButton beng;
    private javax.swing.JTextField drank;
    private javax.swing.JTextField index;
    private javax.swing.JTextField irank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> stream;
    private javax.swing.JTextField zcore;
    // End of variables declaration//GEN-END:variables
}
