/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class Subject extends javax.swing.JPanel {

    private Main main;

    /**
     * Creates new form Subject
     */
    public Subject() {
        initComponents();
    }
    Subject(Main main) {
        initComponents();
        this.main=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cre = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        name2 = new javax.swing.JLabel();
        subjectcode = new javax.swing.JTextField();
        name3 = new javax.swing.JLabel();
        credits = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        name5 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        addresults = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD SUBJECTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cre.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cre.setText("03) NUMBER OF CREDITS :");
        jPanel1.add(cre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 50));

        cost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        jPanel1.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 220, 30));

        name1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name1.setText("07) TYPE :");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 270, 50));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 220, 30));

        name2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name2.setText("02) SUBJECT CODE :");
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 270, 50));

        subjectcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subjectcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectcodeActionPerformed(evt);
            }
        });
        jPanel1.add(subjectcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 220, 30));

        name3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name3.setText("01) NAME :");
        jPanel1.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 270, 50));

        credits.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });
        jPanel1.add(credits, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 80, 30));

        name4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name4.setText("04) COST :");
        jPanel1.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 270, 50));

        type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPULSORY", "OPTIONAL" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 270, 30));

        name5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name5.setText("05) FACULTY :");
        jPanel1.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 270, 50));

        name6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name6.setText("06) ACADEMIC YEAR :");
        jPanel1.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 270, 50));

        name7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name7.setText("07) SEMESTER :");
        jPanel1.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 270, 50));

        faculty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCHOOL OF ENGINEERING", "SCHOOL OF COMPUTING", "SCHOOL OF  BUSINESS" }));
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });
        jPanel1.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 270, 30));

        year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST YEAR", "SECOND YEAR", "THIRD YEAR", "FORTH YEAR" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 270, 30));

        semester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST SEMESTER", "SECOND SEMESTER" }));
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });
        jPanel1.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 270, 30));

        addresults.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addresults.setText("ADD SUBJECT");
        jPanel1.add(addresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 180, 40));

        cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void subjectcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectcodeActionPerformed

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditsActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addresults;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel cre;
    private javax.swing.JTextField credits;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JTextField subjectcode;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
