/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import static nsbm.Main.load;

/**
 *
 * @author Pramuditha Kaushalya
 */
public class view extends javax.swing.JPanel {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nic1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        faculty = new javax.swing.JTextField();
        nic4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        home = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        intake = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VIEW STUDENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("ADDRESS :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 270, 50));

        mobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 220, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 160, 40));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setText("NIC NUMBER :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, 50));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setText("FACULTY :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 270, 50));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setText("CONTACT :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 270, 50));

        name.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        name.setText("NAME :");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 270, 50));

        nic1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 300, 50));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 280, -1));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setText("HOME");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 140, 30));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setText("MOBILE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 140, 30));

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 690, 30));

        faculty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });
        add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 220, 30));

        nic4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nic4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic4ActionPerformed(evt);
            }
        });
        add(nic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 690, 30));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setText("EMAIL :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 270, 50));

        home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 220, 30));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel11.setText("INTAKE :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 270, 50));

        intake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        intake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeActionPerformed(evt);
            }
        });
        add(intake, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 220, 30));

        status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 220, 30));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel12.setText("STATUS :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 270, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 610, 160, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("DELETE");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 610, 160, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("SEARCH");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    private void nic4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nic4ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void intakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intakeActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearText();
        Student studentForm = new Student();
        load.removeAll();
        load.add(studentForm);
        load.repaint();
        load.revalidate();
        studentForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clearText(){
        name.setText("");
        address.setText("");
        home.setText("");
        mobile.setText("");
        email.setText("");
        intake.setText("");
        faculty.setText("");
        status.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField email;
    private javax.swing.JTextField faculty;
    private javax.swing.JTextField home;
    private javax.swing.JTextField intake;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField nic4;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
